services:
  - type: web
    name: connection-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k gevent -w 1 app:app
    autoDeploy: true
    branch: main
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://postgres:password@db:5432/appdb
      - key: SECRET_KEY
        value: super-secret-key
      - key: GRAPHHOPPER_API_KEY
        value: your-graphhopper-key