services:
  - type: web
    name: connection-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k eventlet -w 1 app:app
    autoDeploy: true
    branch: main
    envVars:
      - key: FLASK_ENV
        value: production
